[meta]
name = "Speedrun"
author = "Greep"
category = "Speedrunning"
siteid = 199

version = "1.0.0"

[script]
imports = [ "Permissions.as", "Formatting.as" ]
dependencies = [ "PlayerState" ]

timeout = 0