[meta]
name = "Speedrun"
author = "Greep"
category = "Speedrunning"
siteid = 199

version = "1.0.6"

[script]
imports = [ "Permissions.as", "Formatting.as" ]
dependencies = [ "PlayerState" ]
optional_dependencies = [ "ChaosMode" ]

timeout = 0
